
library(here)
source(here('analysis', 'manual', 'BindInferences.R'))

dlt_series
series <- 441
series <- 192

series <- dlt_series[6]

library(dplyr)
library(ggplot2)

# Data & fits
dlt %>% 
  filter(AnalysisSeriesId == series) %>% 
  ggplot(aes(x = DoseLevelN, y = ProbEvent)) + 
  geom_point(aes(size = n)) + 
  geom_line(aes(y = .fitted, group = Model, col = Model), 
            data = dlt_model_fitted %>% 
              filter(AnalysisSeriesId == series))

# Params
dlt_model_params %>% 
  filter(AnalysisSeriesId == series) %>% 
  filter(Variable %in% c('E0', 'ED50', 'E0 + EMax', 'EMax', 'N')) %>% 
  ggplot(aes(x = Model, y = estimate)) + 
  geom_point() + 
  facet_wrap( ~ Variable, ncol = 2, scales = 'free')


# Manufactured example
seed <- 8976673 # Generated by mashing number-pad
true_prob <- c(0.01, 0.07, 0.12, 0.25, 0.47, 0.52)
n_dose <- length(true_prob)
df_x <- map(true_prob, ~ rbernoulli(n = 100, p = .x))
df_y <- imap_dfr(df_x, ~ list(
  n = length(.x),
  Dose = .y, DoseLevel = .y, DoseLevelN = .y, 
  Events = sum(.x), ProbEvent = mean(.x)))
df <- expand_binary_outcomes_df(df_y)
newdata <- tibble(DoseLevelN = 1:6, Event = 0) %>% as.data.frame()

model1 <- fitMod(DoseLevelN, Event, data = df,  model = "sigEmax",
                bnds = defBnds(mD = max(df$DoseLevelN))$sigEmax)
fitted1 <- broom::augment(model1, newdata = newdata) %>% 
  ungroup() %>% 
  mutate(AnalysisSeriesId = series, Model = 'Maximum likelihood')

model2 <- fit_type2_brms_model_p2(df, seed, object_name = NULL)
fitted2 <- broom.mixed::augment(model2, newdata = newdata) %>% 
  ungroup() %>% 
  mutate(AnalysisSeriesId = series, Model = 'Bayesian')

fitted_df <- bind_rows(fitted1, fitted2)
library(scales)
mycols <- hue_pal()(2) 

curve1_lower <- fitted1 %>% filter(DoseLevelN == 1) %>% pull(.fitted)
curve1_upper <- fitted1 %>% filter(DoseLevelN == n_dose) %>% pull(.fitted)
curve2_lower <- fitted2 %>% filter(DoseLevelN == 1) %>% pull(.fitted)
curve2_upper <- fitted2 %>% filter(DoseLevelN == n_dose) %>% pull(.fitted)

df_y %>% 
  ggplot(aes(x = DoseLevelN, y = ProbEvent)) + 
  geom_point(aes()) + 
  geom_line(aes(y = .fitted, group = Model, col = Model), data = fitted_df) + 
  geom_hline(yintercept = c(0, 1), col = 'red', linetype = 'dashed') + 
  scale_x_continuous(name = 'Dose', breaks = 1:6) + 
  labs(y = 'Prob(Event)') + 
  theme(legend.position = 'bottom') + 
  # annotate("linerange", x = 6.1, ymin = 0.0652, ymax = 0.557, col = mycols[2]) + 
  annotate("segment", x = 6.2, xend = 6.2, 
           y = curve1_lower, yend = curve1_upper, 
           col = mycols[2], 
           arrow = arrow(angle = 20, length = unit(3, "mm"),
                         ends = "both", type = "closed")) + 
  annotate("segment", x = 6.1, xend = 6.1, 
           y = curve2_lower, yend = curve2_upper, 
           col = mycols[1],
           arrow = arrow(angle = 20, length = unit(3, "mm"),
                         ends = "both", type = "closed")) -> p; p
